### ISSUE TITLE
Enforce CHANGELOG file/GitHub tags

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/sbt-org-policies#21]
All the projects using this plugin should contain a CHANGELOG file, by default, with this appearance:

```

## Changelog

## Version X.X.X

Date: 2017-01-26

- ...
- ...

## Version X.X.X

Date: 2016-11-14

- ...
- ...

```

- [x] Template for CHANGELOG.md - #95
- [x] Create a new sbt task (`orgUpdateChangelog`) - #96
- [x] Update GitHubOps for retrieving changelog information - #97
- [x] Modify the current release process - #98
- [x] Include `release` as apart of the `orgAfterCISuccess` - #99

**Comment by juanpedromoreno** [comment]
Blocked by https://github.com/47deg/github4s/issues/68

**Comment by juanpedromoreno** [comment]
This ticket will remain (without story points) as a placeholder Story until all the subtickets are completed.
